language: c

addons:
  apt:
    packages:
    - cmake
    - make
    - libsdl2-dev

compiler:
    - clang

install:
	export C_INCLUDE_PATH=$C_INCLUDE_PATH:`pkg-config --cflags sdl2`

script:
    - mkdir build
    - cd build && cmake .. && make

