language: c

addons:
  apt:
    packages:
    - cmake
    - make
    - libsdl2-dev
    sources:
    - zoogie/sdl2-snapshots

compiler:
    - clang

install:
    - ./test

script:
    - mkdir build
    - cd build && cmake .. && make

